### PR TITLE
added minor changes to create_link method

### LINKED ISSUE #70: Incorrect Label on newly created link
When I create a new link through gns3fy, lets say:
lab.create_link("Switch", "Ethernet0", "Ubuntu18.04", "eth0")

it adds the label name of "0/0" for all connections rather than the appropriate names Ethernet0 & eth0. Is it possible that this can be revised or is this a issue with the API limitations? Thanks.

### PR DESCRIPTION
**Pull request by andrew-grove**
Changed create_link method so that it sets the interface label text as the port name. fixes #70

### CODE REVIEW

**Comment by davidban77** [comment]
Thanks! now I see what it was missing!.

This is great, can you change the PR to merge agains the `develop` branch instead of the `master`? That way I can check/change tests against this specific method.

Thanks!

**Comment by andrew-grove** [comment]
I changed the PR to merge with the develop branch. Hopefully I did it correctly.

**Comment by Krlosromero** [comment]
LGTM @davidban77

**Comment by theister-xan** [comment]
any plans to merge this into master?  We recently noticed the same behavior and traced it down to the same source.
Was about to create an issue/PR, but now i found this.

**Comment by davidban77** [comment]
@theister-xan thanks for pointing out, will be merging it to master soon and release a patch. In the meantime you can build from the `develop` branch

**Pull request merged**
